name: Build and Push Docker Image to Azure Container Registry
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_SERVER }}/${{ github.repository }}:${{ github.event.inputs.tag }}
          build-args:
            steam_user=${{ secrets.STEAM_USER }}
            steam_user=${{ secrets.STEAM_PASSWORD }}
